name: 'Continuous Integration'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        topic-file: 'nextjs/fundamentals.md'
        output-dir: 'docs'