name: 'Continuous Integration'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  OPENAI_API_TYPE: ${{ vars.OPENAI_API_TYPE }}
  OPENAI_API_BASE: ${{ vars.OPENAI_API_BASE }}
  OPENAI_ENGINE: ${{ vars.OPENAI_ENGINE }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
jobs:
  build:
    permissions: 'read-all|write-all'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        topic-file: 'nextjs/fundamentals.md'
        output-dir: 'docs'