name: 'Continuous Integration'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  OPENAI_ENGINE: ${{ envs.OPENAI_ENGINE }}
  OPENAI_ENGINE_REP: ${{ vars.OPENAI_ENGINE_REP }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Test'
      run: | 
        echo "variable from shell environment : $OPENAI_ENGINE"
        echo "variable from repository var : $OPENAI_ENGINE_REP"

    - uses: actions/checkout@v2
    - uses: ./
      with:
        topic-file: 'nextjs/fundamentals.md'
        output-dir: 'docs'