name: 'Continuous Integration'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  OPENAI_ENGINE: ${{ vars.OPENAI_ENGINE }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: | 
      echo "variable from shell environment : $env_var"
    - uses: actions/checkout@v2
    - uses: ./
      with:
        topic-file: 'nextjs/fundamentals.md'
        output-dir: 'docs'